# Generated by Django 5.2.17 on 2026-09-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('original_image', models.ImageField(upload_to='maps/%Y/%m/%d/')),
                ('datum', models.CharField(choices=[('AUTO', 'Auto-detect via AI'), ('WGS84', 'WGS 84 (World Geodetic System)'), ('ED50', 'ED50 (European Datum 1950)'), ('NAD83', 'NAD83 (North American Datum 1983)'), ('NAD27', 'NAD27 (North American Datum 1927)'), ('ARC1960', 'Arc 1960 (East Africa)'), ('MINNA', 'Minna (Nigeria)'), ('TOKYO', 'Tokyo Datum (Japan)')], default='AUTO', max_length=50)),
                ('utm_zone', models.IntegerField(blank=True, help_text='UTM Zone number (1-60). Leave empty for auto-detection.', null=True)),
                ('hemisphere', models.CharField(choices=[('N', 'Northern Hemisphere'), ('S', 'Southern Hemisphere')], default='N', max_length=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('extracted_data', models.JSONField(blank=True, default=dict, help_text='Raw metadata and ground control points extracted by Gemini Vision.')),
                ('transformed_data', models.JSONField(blank=True, default=dict, help_text='Calculated WGS84 coordinates, bounding box, and Leaflet overlay payload.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
