# Generated by Django 5.2.17 on 2026-10-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedmap',
            name='raster_preview',
            field=models.ImageField(blank=True, help_text='Rasterized PNG preview for Mapbox overlay and vision models (generated for PDFs).', null=True, upload_to='previews/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='processedmap',
            name='original_image',
            field=models.FileField(help_text='Uploaded map file (PDF, PNG, JPEG, TIFF, WebP).', upload_to='maps/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='processedmap',
            name='transformed_data',
            field=models.JSONField(blank=True, default=dict, help_text='Calculated WGS84 coordinates, bounding box, and Mapbox overlay payload.'),
        ),
    ]
